Repository DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS, pull requests merged in 2024-12, with the labels that each got.

#103 [Chore] 월간 달력 그리기
  Spha/Shared/Extensions/Date+.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 💻 Logic, 🎨 UI

#104 Feat: #95-watch 알림 터치 시 화면 이동
  Spha/SphaWatch Watch App/Manager/WatchRouterManager.swift
Labels: 💻 Logic

#107 Fix: #106-IOS 호흡뷰 문구 수정 및 인디케이터 수정
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
Labels: 🐞 Bug & Fix, 🪢 Chore

#108 [Fix] 호흡 화면 흰 화면 및 호흡 횟수 측정 오류
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
Labels: 🐞 Bug & Fix

#110 [Fix] 호흡 화면 싱크 맞추기
  Spha/Shared/Managers/BreathingManager.swift
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
  Spha/Spha/Views/Home/MP4PlayerView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
Labels: 🐞 Bug & Fix

#112 Chore: #111-버튼 글자 수정
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
Labels: 🪢 Chore, 🎨 UI

#114 [Chore] 달력 개수 수정
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 🪢 Chore

#116 [Feat] watchOS workoutSession 적용
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/SphaWatch Watch App/Manager/WorkoutManager.swift
  Spha/SphaWatch Watch App/SphaWatchApp.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
Labels: 🐞 Bug & Fix, 🪢 Chore

#125 [Fix] 알림 지속되는 버그 픽스
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
Labels: 🐞 Bug & Fix

#128 [Fix] 통계뷰 기기대응
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/MonthlyCalendarSheetView.swift
Labels: 🐞 Bug & Fix, 🎨 UI

#131 [Fix] 통계뷰 스와이프 버그 픽스
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 🐞 Bug & Fix, 💻 Logic

#130 [Fix] hrv 데이터 업데이트 문제 픽스
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
Labels: 🐞 Bug & Fix, 💻 Logic
