Repository DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS, pull requests merged in 2024-11, with the labels that each got.

#7 [Feat] HealthKit HRV Data Fetch 구현 및 테스트
  Spha/Shared/Managers/HealthKitManager.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitTestView.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Info.plist
  Spha/Spha/Spha.entitlements
  Spha/Spha/SphaApp.swift
Labels: 💻 Logic

#8 [Feat] 로컬 알림 구현
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/SphaWatch Watch App/Manager/NotificationManager.swift
  Spha/SphaWatch Watch App/Notification/NotificationView.swift
  Spha/SphaWatch Watch App/Notification/PushNotificationPayload.apns
  Spha/SphaWatch Watch App/SphaWatchApp.swift
Labels: 🪢 Chore, 💻 Logic

#11 [Feat] HRV 모니터링 및 백그라운드 알림 (간이 테스트)
  Spha/Shared/Managers/HealthKitManager/AppDelegate.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitTest/HealthKitManager+TestData.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitTest/HealthKitTestView.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitTestView.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Spha.entitlements
  Spha/Spha/SphaApp.swift
Labels: 💻 Logic

#14 [Feat] 호흡 세션 뷰 구현
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingOutroView.swift
  Spha/Spha/Views/Home/MainView.swift
Labels: 💻 Logic, 🎨 UI

#19 Fix: #18-누락된 HealthKitTest 폴더 재연결
  Spha/Spha.xcodeproj/project.pbxproj
Labels: 🐞 Bug & Fix

#20 [Feat] 주간 캘린더 구현
  Spha/Shared/Extensions/Date+.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/SphaApp.swift
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/WeeklyCalendarHeaderViewModel.swift
  Spha/SphaWatch Watch App/SphaWatchApp.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 💻 Logic, 🎨 UI

#22 [Feat] MindfulSession 기본 작업
  Spha/Shared/Managers/MindfulSessionManager/MindfulSessionManager.swift
  Spha/Shared/Managers/MindfulSessionManager/MindfulSessionTestView/MindfulSessionTestView.swift
  Spha/Spha.xcodeproj/project.pbxproj
Labels: 💻 Logic

#27 [Chore] 모델 수정
  Spha/Shared/Models/MindDustLevel.swift
  Spha/Shared/Models/TodayStress.swift
  Spha/Spha.xcodeproj/project.pbxproj
Labels: 🪢 Chore

#28 [Feat] WatchOS 호흡 세션 뷰 구현
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha.xcodeproj/xcshareddata/xcschemes/Spha.xcscheme
  Spha/Spha.xcodeproj/xcshareddata/xcschemes/SphaWatch Watch App.xcscheme
  Spha/Spha/SphaApp.swift
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/SphaWatch Watch App/Manager/WatchRouterManager.swift
  Spha/SphaWatch Watch App/SphaWatchApp.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingExitView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingSelectionView.swift
  Spha/SphaWatch Watch App/Views/ContentView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainView.swift
Labels: 🪢 Chore, 🎨 UI

#30 [Chore] 디자인 시스템 등록
  Spha/Shared/Extensions/Color+.swift
  Spha/Shared/Extensions/Text+.swift
  Spha/Shared/Resources/Font/AppleSDGothicNeoM.ttf
  Spha/Shared/Resources/Font/AppleSDGothicNeoSB.ttf
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Info.plist
Labels: 🪢 Chore, 🎨 UI

#31 [Revert] "[Chore] 디자인 시스템 등록"
  Spha/Shared/Extensions/Color+.swift
  Spha/Shared/Extensions/Text+.swift
  Spha/Shared/Resources/Font/AppleSDGothicNeoM.ttf
  Spha/Shared/Resources/Font/AppleSDGothicNeoSB.ttf
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Info.plist
Labels: 🐞 Bug & Fix

#38 [Chore] 호흡 세션 뷰 모델 분리
  Spha/Shared/Managers/BreathingManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
  Spha/Spha/Views/Home/MainViewModel.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
Labels: 🪢 Chore

#40 [Chore] 일일 통계 UI 구현
  Spha/Shared/Models/StressLevel.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 🪢 Chore, 🎨 UI

#48 [Chore] MainView Info 화면 UI 구현
  Spha/Shared/Extensions/Font+.swift
  Spha/Shared/Resources/Font/AppleSDGothicNeoR.ttf
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Info.plist
  Spha/Spha/Views/Home/MainInfoView.swift
Labels: 🪢 Chore, 🎨 UI

#50 [Feat] 일일 스트레스 추이 그래프 데이터 연결
  Spha/Shared/Models/DailyStressRecord.swift
  Spha/Shared/Models/StressLevel.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 🪢 Chore, 💻 Logic, 🎨 UI

#53 [Feat] 마음챙기기 데이터 연결
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
Labels: 🪢 Chore, 💻 Logic

#60 [Feat] onboarding auth
  Spha/Shared/Managers/HealthKitManager/AppDelegate.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/MindfulSessionManager/MindfulSessionManager.swift
  Spha/Shared/Managers/MindfulSessionManager/MindfulSessionTestView/MindfulSessionTestView.swift
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/SphaApp.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
Labels: 🪢 Chore

#62 [Feat] IOS 호흡 세션 MindfulSession 연동 저장
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingOutroView.swift
  Spha/Spha/Views/Breathing/BreathingOutroViewModel.swift
Labels: 💻 Logic

#63 [Feat] WatchOS 호흡 세션 MindfulSession 연동 저장
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/SphaWatch Watch App/SphaWatch Watch App.entitlements
  Spha/SphaWatch Watch App/SphaWatchApp.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroViewModel.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusViewModel.swift
  Spha/SphaWatch-Watch-App-Info.plist
Labels: 🪢 Chore, 💻 Logic

#64 [Chore] onboarding main UI 수정 및 화면 설정
  Spha/Shared/Helper/FilePathHelper.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Assets.xcassets/SPHAlogo.imageset/Contents.json
  Spha/Spha/Assets.xcassets/SPHAlogo.imageset/SPHAlogo.png
  Spha/Spha/Assets.xcassets/mainButton.imageset/Contents.json
  Spha/Spha/Assets.xcassets/mainButton.imageset/mainButton.png
  Spha/Spha/SphaApp.swift
  Spha/Spha/Views/Home/MP4PlayerView.swift
  Spha/Spha/Views/Home/MainInfoView.swift
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Home/MainViewModel.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
  Spha/Spha/Views/Onboarding/OnboardingStartView.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 🎨 UI

#65 [Chore] WatchOS 호흡 세션 종료시 햅틱 중단 로직 추가
  Spha/SphaWatch Watch App/Manager/HapticManager.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingExitView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
Labels: 🐞 Bug & Fix, 🪢 Chore

#72 [Chore] UI 수정 및 데이터 호출 최적화
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Home/MainViewModel.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/MindfulSessionAuth.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
Labels: 🐞 Bug & Fix, 🪢 Chore

#73 [Chore] WatchOS MainView UI 수정
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMP4PlayerView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusView.swift
Labels: 🪢 Chore

#74 [Feat] NotificationManager 통합
  Spha/Shared/Managers/NotificationManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/SphaWatch Watch App/Notification/NotificationView.swift
Labels: 🪢 Chore, 💻 Logic

#81 [Chore] 배포용 파일 정리
  Spha/Shared/Managers/HealthKitManager/HealthKitTest/HealthKitManager+TestData.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitTest/HealthKitTestView.swift
  Spha/Shared/Managers/MindfulSessionManager/MindfulSessionTestView/MindfulSessionTestView.swift
  Spha/Shared/Managers/NotificationManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/SphaWatch Watch App/Notification/NotificationView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusViewModel.swift
Labels: 🪢 Chore

#86 [Chore] 네비게이션 커스텀
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
Labels: 🎨 UI

#89 [Feat] Notification entry & Background Alert Fix
  Spha/Shared/Managers/HealthKitManager/AppDelegate.swift
  Spha/Shared/Managers/HealthKitManager/HealthKitManager.swift
  Spha/Shared/Managers/NotificationManager.swift
  Spha/Shared/Managers/RouterManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Info.plist
  Spha/Spha/Views/Home/MP4PlayerView.swift
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 💻 Logic

#91 [Fix] iOS BreathingMainView MP4 영상 끊김 해결
  Spha/Shared/Models/BreathingPhase.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
  Spha/Spha/Views/Breathing/MultiMP4PlayerView.swift
Labels: 🐞 Bug & Fix, 🎨 UI

#93 [Fix] 마음구슬 로직 통일
  Spha/Shared/Models/DailyStressRecord.swift
  Spha/Spha.xcodeproj/xcshareddata/xcschemes/SphaWatch Watch App.xcscheme
  Spha/Spha/Assets.xcassets/AppIcon.appiconset/1024.png
  Spha/Spha/Assets.xcassets/AppIcon.appiconset/AppIcon 1.png
  Spha/Spha/Assets.xcassets/AppIcon.appiconset/AppIcon.png
  Spha/Spha/Assets.xcassets/AppIcon.appiconset/Contents.json
  Spha/Spha/Assets.xcassets/MindfulSessionIcon.imageset/Contents.json
  Spha/Spha/Assets.xcassets/NotiAlert.imageset/Contents.json
  Spha/Spha/Assets.xcassets/SPHAlogo.imageset/Contents.json
  Spha/Spha/Assets.xcassets/WatchGuideImage.imageset/Contents.json
  Spha/Spha/Assets.xcassets/mainButton.imageset/Contents.json
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Home/MainViewModel.swift
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsViewModel.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusViewModel.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 💻 Logic

#94 [Chore] WatchOS Breathing 세션 가이딩 영상 뷰로 수정
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingAnimationView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMP4PlayerView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
Labels: 🐞 Bug & Fix, 🎨 UI

#100 [Fix] iOS 버그 종합 수정
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Assets.xcassets/WatchGuideImage.imageset/Contents.json
  Spha/Spha/Assets.xcassets/WatchGuideImage.imageset/WatchGuideImage.png
  Spha/Spha/Assets.xcassets/healthAuthImage.imageset/Contents.json
  Spha/Spha/Assets.xcassets/healthAuthImage.imageset/healthAuthImage.png
  Spha/Spha/Assets.xcassets/watchGuideImage.imageset/Contents.json
  Spha/Spha/Assets.xcassets/watchGuideImage.imageset/watchGuideImage.png
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Home/MainViewModel.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/BreathingGuide.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/ExplainMenu.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/HealthKitHRVAuth.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/NotificationAuth.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/WatchGuide.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
  Spha/Spha/Views/Onboarding/OnboardingStartView.swift
Labels: 🐞 Bug & Fix, 🪢 Chore, 💻 Logic, 🎨 UI

#102 [Chore] 일일 통계 UI 수정
  Spha/Shared/Extensions/Date+.swift
  Spha/Spha/Assets.xcassets/GrayscaleColors/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays.colorset/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays2.colorset/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays3.colorset/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays4.colorset/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays5.colorset/Contents.json
  Spha/Spha/Assets.xcassets/GrayscaleColors/grays6.colorset/Contents.json
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
Labels: 🎨 UI
