Repository DeveloperAcademy-POSTECH/2024-MacC-A7-92NMS, pull requests merged in 2025-01, with the labels that each got.

#134 [Chore] BreathingView 모달 변경
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingOutroView.swift
  Spha/Spha/Views/Home/MainView.swift
Labels: 🪢 Chore

#137 [Chore] 로컬라이제이션 작업
  Spha/Shared/Extensions/Date+.swift
  Spha/Shared/Models/BreathingPhase.swift
  Spha/Shared/Models/MindDustLevel.swift
  Spha/Shared/Models/StressLevel.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
  Spha/Spha/Views/Breathing/BreathingOutroView.swift
  Spha/Spha/Views/Home/MainInfoView.swift
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/BreathingGuide.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/ExplainMenu.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/HealthKitHRVAuth.swift
  Spha/Spha/Views/Onboarding/IndicatorViews/WatchGuide.swift
  Spha/Spha/Views/Onboarding/OnboardingContainerView.swift
  Spha/Spha/Views/Onboarding/OnboardingStartView.swift
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
  Spha/Spha/Views/Statistics/MonthlyCalendarSheetView.swift
  Spha/Spha/en.lproj/Localizable.strings
  Spha/Spha/ko.lproj/Localizable.strings
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingExitView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingOutroView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingSelectionView.swift
  Spha/SphaWatch Watch App/Views/Home/WatchMainStatusView.swift
Labels: 🪢 Chore

#142 [Feat] 햅틱 수정 및 추가 작업
  Spha/Shared/Managers/BreathingManager.swift
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha.xcodeproj/xcshareddata/xcschemes/SphaWatch Watch App.xcscheme
  Spha/Spha/Managers/HapticManager.swift
  Spha/Spha/Views/Breathing/BreathingMainView.swift
  Spha/Spha/Views/Breathing/BreathingMainViewModel.swift
  Spha/Spha/Views/Home/MainView.swift
  Spha/Spha/en.lproj/Localizable.strings
  Spha/Spha/ko.lproj/Localizable.strings
  Spha/SphaWatch Watch App/Manager/HapticManager.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainView.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingMainViewModel.swift
  Spha/SphaWatch Watch App/Views/Breathing/WatchBreathingSelectionView.swift
Labels: 🪢 Chore

#144 [Feat] RefreshMainScreen
  Spha/Spha/Views/Home/MainView.swift
Labels: 💻 Logic, 🎨 UI

#146 [Chore] UI 수정 및 버전 업데이트
  Spha/Spha.xcodeproj/project.pbxproj
  Spha/Spha/Views/Statistics/DailyStatisticsView.swift
Labels: 🪢 Chore, 🎨 UI
